# Generated by Django 5.0.8 on 2024-08-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=0, verbose_name="Поточний баланс"),
        ),
    ]
