# Generated by Django 5.0.8 on 2024-08-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0002_alter_user_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="limit_balance",
            field=models.IntegerField(verbose_name="Недоторканний запас"),
        ),
    ]
