# Generated by Django 5.0.8 on 2024-08-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0003_alter_user_limit_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="expenses",
        ),
        migrations.RemoveField(
            model_name="user",
            name="incomes",
        ),
    ]
