# Generated by Django 5.0.8 on 2024-08-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0004_remove_user_expenses_remove_user_incomes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="limit_balance",
            field=models.IntegerField(default=0, verbose_name="Недоторканний запас"),
        ),
    ]
